name: Zolmeister
description: Zolmeister - Blog
meta_description: "Zolmeister - Blog - by Zoli Kahan"

permalink: :year/:month/:title.html
rss_path: feeds/posts/
rss_name: default

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

#baseurl: 'https://zolmeister.com'

# Details for the RSS feed generator
url:            'https://zolmeister.com'
author:         'Zoli Kahan'
