name: Zolmeister
description: Zolmeister - Blog
meta_description: "Zolmeister - Blog - by Zoli Kahan"

permalink: :year/:month/:title.html

gems: [jekyll-paginate, redcarpet, jekyll-feed]
markdown: redcarpet
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'https://zolmeister.com'
author:         'Zoli Kahan'
feed:
  path: feeds/posts/default
