name: Zolmeister
description: Blogging about stuffs
meta_description: "Zolmeister, blog"

permalink: :year/:month/:title.html
rss_path: feeds/posts/
rss_name: default

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://zolmeister.com'
author:         'Zoli Kahan'
